spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: @spring.profiles.active@
  application:
    name: yours-tool-springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      connection-timeout: 30000
      # 最小连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 20
      # 事务自动提交
      auto-commit: true
      # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      idle-timeout: 600000
      # 连接池名字
      pool-name: DateSourceHikariCP
      # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      max-lifetime: 1800000
      # 连接测试语句
      connection-test-query: SELECT 1
  redis:
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 5000
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 5000
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000

mybatis-plus:
  mapper-package: yours.tool.springboot.mapper
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: yours.tool.springboot.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
    #mybatis-plus配置控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cacheEnabled: false
  global-config:
    banner: false
    db-config:
      id-type: input
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      logic-delete-field: isDelete

logging:
  level:
    com.xkcoding.rbac.security: debug

knife4j:
  # 是否开启Knife4j增强模式
  enable: true
  # 是否开启一个默认的跨域配置,该功能配合自定义Host使用
  cors: true
  # 是否开启生产环境保护策略
  production: true
  # 对Knife4j提供的资源提供BasicHttp校验,保护文档
  info:
    title: yours-tool接口文档
  basic:
    enable: false
    username: admin
    password: 123456
  # 前端Ui的个性化配置属性
  setting:
    # 调试Tab是否显示AfterScript功能,默认开启
    enableAfterScript: false
    # Ui默认显示语言,目前主要有两种:中文(zh-CN)、英文(en-US)
    language: zh-CN
    # 是否显示界面中SwaggerModel功能
    enableSwaggerModels: false
    # 重命名SwaggerModel名称,默认
    swaggerModelName: 实体类列表
    # 是否显示界面中"文档管理"功能
    enableDocumentManage: true