server:
  port: 3322

spring:
  datasource:
#    url: jdbc:mysql://192.168.0.172:3306/link_edp_test1.3?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowPublicKeyRetrieval=true
#    username: root
#    password: wswbh
    url: jdbc:mysql://192.168.0.149:3306/link_edp_test3.0?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password:

knife4j:
  basic:
    enable: false
    username: admin
    password: 123456